server:
  port: 9999

spring:
  resources:
       static-locations: classpath:/
  http:
      encoding:
        force: true
        charset: UTF-8
#  freemarker配置
  freemarker:
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    allow-request-override: false
    request-context-attribute: req  #req访问request
    suffix: .html  #后缀名 不写默认是.ftl
#    suffix: .ftl  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format:
#  jsp配置
  mvc:
     view:
      prefix: /WEB-INF/jsp/ # Read From Web Resources Dir
      suffix: .jsp
# thymeleaf
  thymeleaf:
    cache: false